{{- if .Values.templates.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: hcloud
  labels:
    clusterctl.cluster.x-k8s.io/move: ""
    {{- include "kubecraft.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: "{{ .Values.clusterapi.infrastructure.hetzner.token }}"

{{- end }}