{{- range .Values.helmreleases }}
{{- if or (not .spec) (not .spec.kind ) }}
{{- $name := .spec.fullnameOverride | default (print $.Release.Name "-" .metadata.name ) }}
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  labels:
    app.kubernetes.io/instance: {{ $.Release.Namespace | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
    app.kubernetes.io/part-of: flux
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
spec:
  url: https://github.com/kubecraft-k8s/kubecraft-charts
  interval: 5m
  ref:
    branch: main
{{- end }}
---
{{- end }}