{{- range .Values.helmreleases }}
{{- if .spec.chart.source.kind eq "HelmRepository"}}
{{- $name := .metadata.name  }}
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Release.Namespace | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: flux
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
{{ with .spec.chart.source.labels }}{{ toYaml . | indent 4 }}{{ end }}
{{- with .spec.chart.source.annotations }}
  annotations: {{ toYaml . | nindent 4 }}
{{- end }}
  name: {{- .metadata.name  }}
  namespace: {{ .Release.Namespace }}
spec:
  url: {{ .spec.chart.source.url }}
  {{- if .spec.chart.source.interval }}
  interval: {{ .spec.chart.source.interval }}
  {{- end }}
  {{- if ..spec.chart.source.type }}
  type: {{ .spec.chart.source.type }}
  {{- end }}
{{- end }}
{{- end }}