{{/*TODO: Allow setting existingRelease or helmreleaseRef to specified a shared dependency*/}}
{{- range .Values.helmreleases }}
{{- $name := .metadata.name  }}
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  labels:
    app.kubernetes.io/instance: {{ $.Release.Namespace | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
    app.kubernetes.io/part-of: flux
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
  {{- with .labels }}{{ toYaml . | indent 4 }}{{ end }}
  {{- with .annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  name:  {{ $name }}
  namespace: {{ $.Release.Namespace }}
spec:
  install:
    createNamespace: true
  releaseName: {{ $name }}
  targetNamespace: {{ .targetNamespace | default $name }}
  dependsOn: {{ toYaml .dependsOn | nindent 4 }}
  storageNamespace: {{ .storageNamespace | default "flux-system" }}
  chart:
    spec:
      interval: {{ .interval | default "1m" }}
      chart: {{ .chart | default "flux2-sync-helm" }}
      sourceRef:
        kind: {{ .type | default "GitRepository" }}
        name: {{ $.Release.Name }}-{{ $name }}
      {{- if .version }}
      version: {{ .version}}
      {{- end }}
  interval: {{ .interval | default "1m" }}
  {{- with .values }}
  values: {{ toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
