{{/*TODO: Allow setting existingRelease or helmreleaseRef to specified a shared dependency*/}}
{{- range .Values.helmreleases }}
{{- $name := .spec.fullnameOverride | default (print $.Release.Name "-" .metadata.name ) }}
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  labels:
    app.kubernetes.io/instance: {{ $.Release.Namespace | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
    app.kubernetes.io/part-of: flux
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
  {{- with .labels }}{{ toYaml . | indent 4 }}{{ end }}
  {{- with .annotations }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
  name:  {{ $name }}
  namespace: {{ $.Release.Namespace }}
spec:
  {{- with .spec.kubeconfig }}
  kubeConfig:
    secretRef:
      name: {{ . }}
  {{- end }}
  install:
    createNamespace: true
  releaseName: {{ .releasename | default $name }}
  targetNamespace: {{ .targetNamespace | default $name }}
  storageNamespace: {{ .storageNamespace | default "flux-system" }}
  {{- with .spec.dependsOn }}
  dependsOn: {{ toYaml . | nindent 4 }}
  {{- end }}
  chart:
    spec:
      interval: {{ .spec.interval | default "1m" }}
      chart: {{ .spec.chart | default "flux2-sync-helm" }}
      sourceRef:
        kind: {{ .spec.kind | default "GitRepository" }}
        name: {{ $name }}
      {{- if .spec.version }}
      version: {{ .spec.version}}
      {{- end }}
  interval: {{ .interval | default "1m" }}
  {{- with .values }}
  values: {{ toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}
