secret:
  create: false
  # -- Data of the secret.
  # For HTTPS repositories the secret must contain username and password fields.
  # For SSH repositories the secret must contain identity, identity.pub and known_hosts fields.
  # Values will be encoded to base64 by the helm chart.
  data: {}
gitRepository:
  spec:
    interval: "5m"
    url: "https://github.com/kubecraft-k8s/kubecraft-charts"
    ref:
      branch: main
helmrelease:
  labels: {}
  annotations: {}
  spec:
    dependsOn: []
    interval: 1m
    targetNamespace: ""
    chart:
      version:
      interval: 1m
      name:
      sourceRef:
        kind: HelmRepository
      values: {}
helmreleases: []