{{- if .Values.templates.enabled }}
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: ccm-hetzner
spec:
  clusterSelector:
    matchLabels:
      codes.danielrichter.kubecraft/extensions.ccm: "true"
  repoURL: https://charts.hetzner.cloud
  chartName: hcloud-cloud-controller-manager
  namespace: kube-system
  version: "{{ .Values.clusterapi.addon.ccmHetzner.version}}"
  releaseName: ccm-hetzner
  options:
    install:
      createNamespace: true
  valuesTemplate: |
    fullnameOverride: ccm-hetzner
{{- end }}