{{- if .Values.templates.enabled }}
apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: cni-cillium
spec:
  clusterSelector:
    matchLabels:
     codes.danielrichter.kubecraft/extensions.cni: "true"
  repoURL: https://helm.cilium.io/
  chartName: cilium
  namespace: kube-cillium
  version: "{{ .Values.clusterapi.addon.cniCillium.version}}"
  releaseName: cni-cillium
  options:
    install:
      createNamespace: true
  valuesTemplate: |
    fullnameOverride: cni-cillium
{{- end }}