{{- range .Values.providers }}
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: {{ .kind }}
metadata:
  name: {{ .name }}
spec:
{{- with .url}}
  fetchConfig:
    url: {{ . }}
{{- end }}
{{- with .version}}
  version: {{ . }}
{{- end }}
---
{{- end }}