{{- if .Values.templates.enabled }}
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ include "kubecraft.fullname" . }}
  labels:
    codes.danielrichter.kubecraft/extensions.ccm: "true"
    codes.danielrichter.kubecraft/extensions.cni: "true"
    {{- include "kubecraft.labels" . | nindent 4 }}
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.244.0.0/16
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: {{ include "kubecraft.fullname" . }}
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: HetznerCluster
    name: {{ include "kubecraft.fullname" . }}
{{- end }}