{{- if .Values.templates.enabled }}
# TODO: create multiple machinedeployments per worker group
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    nodepool: {{ include "kubecraft.fullname" . }}-md
    {{- include "kubecraft.labels" . | nindent 4 }}
  name: {{ include "kubecraft.fullname" . }}
spec:
  clusterName: {{ include "kubecraft.fullname" . }}
  replicas: {{ .Values.clusterapi.core.replicas }}
  template:
    metadata:
      labels:
        {{- include "kubecraft.labels" . | nindent 8 }}
        nodepool: {{ include "kubecraft.fullname" . }}-md
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ include "kubecraft.fullname" . }}
      clusterName: {{ include "kubecraft.fullname" . }}
      failureDomain: {{ .Values.clusterapi.infrastructure.hetzner.region }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: {{ include "kubecraft.fullname" . }}-md-cax11
      version: {{ .Values.clusterapi.core.kubernetesversion }}
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineHealthCheck
metadata:
  name: {{ include "kubecraft.fullname" . }}-md
  labels:
    {{- include "kubecraft.labels" . | nindent 4 }}
spec:
  clusterName: {{ include "kubecraft.fullname" . }}
  maxUnhealthy: 100%
  nodeStartupTimeout: 10m
  remediationTemplate:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: HCloudRemediationTemplate
    name: {{ include "kubecraft.fullname" . }}-md
  selector:
    matchLabels:
      nodepool: {{ include "kubecraft.fullname" . }}-md
  unhealthyConditions:
    - status: Unknown
      timeout: 180s
      type: Ready
    - status: "False"
      timeout: 180s
      type: Ready
{{- end }}