apiVersion: v1
kind: ServiceAccount
metadata:
  name: podinfo-backup
  annotations:
    "helm.sh/hook": post-install,post-upgrade
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name:  podinfo-backup
  namespace: velero
  annotations:
    "helm.sh/hook": post-install,post-upgrade
rules:
  - apiGroups: [ "velero.io" ]
    resources:
      - backups
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups: [ "velero.io" ]
    resources:
      - schedules
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: podinfo-backup
  namespace: velero
  annotations:
    "helm.sh/hook": post-install,post-upgrade
subjects:
  - kind: ServiceAccount
    name: podinfo-backup
    namespace: {{$.Release.Namespace}}
roleRef:
  kind: Role
  name: podinfo-backup
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: podinfo-backup
  annotations:
    "helm.sh/hook": post-install,post-upgrade
spec:
  template:
    metadata:
      name: podinfo-backup
    spec:
      serviceAccountName: podinfo-backup
      containers:
        - name: podinfo-backup
          image: "velero/velero"
          command: [ "/velero" ]
          args: [ "backup","create","--from-schedule={{.Values.backupname}}","--wait" ]
      restartPolicy: Never
---
