apiVersion: velero.io/v1
kind: Schedule
metadata:
  name: {{ .Values.backupname }}
  namespace: velero
spec:
  schedule: {{ .Values.schedule }}
  template:
    includedResources:
      - deployment
    labelSelector:
      matchLabels:
        x.velero.backup: {{ .Values.backupname }}
